import React from 'react';
import { TextSection } from '../../components/text-section/text-section.component';

const TermsPage = () => (
  <TextSection heading="Terms">
    <h3>
      MOE terms and conditions for website use
    </h3>
    <p>
      Please read these Terms and Conditions For Website Use (the “Terms and Conditions”)
      carefully before using this website and any Imogene content on social media sites
      (including without limitation Facebook and Twitter) (together, the “Site”).
      These Terms and Conditions apply to all visits and use of the Site,
      as well as to the Content (as defined below), information, recommendations,
      products and/or services provided to you on or through the Site.
      If you choose to continue to use or access this Site after having
      the opportunity to read these Terms and Conditions, you recognize
      that Imogene has provided valuable consideration by offering
      this Site free of charge, and in exchange for that valuable consideration,
      you agree to the Terms and Conditions hereof.
      If you do not agree to these Terms and Conditions in their entirety,
      please do not use or access the Site.

      These terms include an agreement to submit claims exclusively to individual
      (non-class) arbitration. See below.
    </p>
    <h3>
      Operator of the Site
    </h3>
    <p>
      This Website is owned and operated by the adidas Group (&quot;Imogene&quot;).
    </p>
    <h3>
      Content on the Site
    </h3>
    <p>
      All of the content featured or displayed on the Site, including, but not limited to,
      logos, icons, trademarks, text, graphics, photographs, images, moving images, sound,
      illustrations and software (&quot;Content&quot;),
      is owned by Imogene International Limited (UK) (&quot;Imogene International&quot;),
      its affiliated companies, its licensors and/or its content
      providers. All elements of the Site including, but not limited to, the general design
      and the Content, can be protected by copyright, moral rights, database rights, trade
      mark and other laws relating to intellectual property rights. Except as explicitly
      permitted under this or another agreement with Imogene International, no portion or
      element of the Site or its Content may be copied or retransmitted via any means.
      The Site, its Content and all related rights shall remain the exclusive property of
      Imogene International, its affiliated companies or its licensors unless otherwise
      expressly agreed. All such rights are reserved.
    </p>
    <h3>
      Copyright and Trade marks
    </h3>
    <p>
      The copyright in all Content is and remains owned by Imogene International,
      its affiliated companies or its licensors as appropriate. Except as may be otherwise
      indicated in specific documents within the Site, you are authorized to view, play,
      print and download Content found on the Site for personal, informational,
      and non-commercial purposes only. You may not modify any of the materials
      and you may not copy, distribute, transmit, display, perform, reproduce, publish,
      license, create derivative works from, transfer or sell any Content.
      You may not re-use any Content without first obtaining the consent of Imogene
      International. For purposes of these Terms and Conditions, the use of any such
      Content on any other website or networked computer environment is prohibited.
      You may not remove any copyright, trade mark or other proprietary notices
      from Content found on the Site.

      In the event you download software (including but not limited to screensavers,
      smart phone applications, icons, videos and wallpapers) from the Site,
      the software, including any files, images incorporated in or generated by
      the software, and data accompanying the software (collectively, the
      “Software”) are licensed to you by Imogene International. Imogene International
      does not transfer title to the Software to you. You own the medium on which
      the Software is recorded, but Imogene International retains full and complete
      title to the Software, and all intellectual property rights therein.
      You may not redistribute, sell, de-compile, reverse engineer, disassemble
      or otherwise reduce the Software to a human-readable form.

      All trade marks, service marks, logos and trade names which appear on products
      of Imogene, product packaging and/or on the Site, whether registered or not
      (including but not limited to: the word mark &quot;Imogene&quot;, the Crown logo,
      the Imogene delta logo remain the
      exclusive property of Imogene International, its affiliated companies
      or its licensors (as appropriate) and are protected by applicable trade
      mark laws and treaties. You may not use, copy, reproduce, republish, upload,
      post, transmit, distribute, or modify any of the Trade Marks in any way,
      including in advertising or publicity pertaining to distribution of materials
      on the Site, without Imogene International’s prior written consent.
      The use of any of the Trade Marks on any other website or network
      computer environment, for example the storage or reproduction of
      (a part of) the Site in any external internet site or the creation
      of links, hypertext, links or deeplinks between the Site and any other
      internet site, is prohibited without the express written consent
      of Imogene International.
    </p>
    <h3>
      Establishing an Account/Profile
    </h3>
    <p>
      In order to purchase products or services from the Site or to access or
      use certain features on the Site, you may be required to establish and
      use a profile or account. When you register for an account or establish
      a profile, you may be asked to create a user ID and choose a password.
      You are responsible for keeping your user ID and password secret and
      confidential and restricting access to that information. You agree that
      you are solely responsible for all activities that occur using your
      user ID and password.
    </p>
    <h3>
      Disclaimer of Warranties
    </h3>
    <p>
      This disclaimer (&quot;Disclaimer&quot;) applies only to your free use of the Site.
      This Disclaimer does not apply to, for example, your purchase of any product
      or service from Imogene. This Disclaimer also does not apply to, for example,
      our offer or advertisement of any Imogene product or service including the content
      of any offer or advertisement on the Site.

      Imogene is not offering this Site, in whole or in part, for sale to you.
      These Terms and Conditions are not a contract for sale, and this Site is not
      a &quot;good&quot; within the meaning of the Uniform Commercial Code.
      Instead, the Site and the Content are free of charge and provided “as is”
      and without any warranties of any kind. Imogene disclaims any and all warranties,
      express or implied, including, but not limited to, implied warranties of merchantability
      and fitness for a particular purpose. There are no warranties which
      extend beyond the description on the face hereof. The information on the
      Site is for general information purposes only and does not constitute advice.

      Imogene does not represent or warrant that the functions contained in this
      Site will be uninterrupted or error-free, that defects will be corrected,
      or that the server that makes the content available will be free of viruses
      or other harmful components. Further, Imogene will not provide for specific
      IT infrastructure or connectivity.
    </p>
    <h3>
      Limitation of Liability
    </h3>
    <p>
      This limitation of liability (“Limitation”) applies only to your free use of
      the Site. This Limitation does not apply to, for example, your purchase of
      any product or service from Imogene. This Limitation also does not apply to,
      for example, our offer or advertisement of any Imogene product or service
      including the content of any offer or advertisement on the Site.

      Your use of the Site is at your own risk. You agree that our sole obligation
      to you is to provide the Site “as is.” Neither Imogene nor any of its employees,
      officers, directors nor any of its agents or any other party involved in
      creating, producing or delivering the Site shall be liable to you or to
      any third party for your use of, or the inability to use, the Site and
      its Content except in cases of (a) gross negligence, recklessness,
      or an act of knowing or intentional willful misconduct; or (b) a violation
      of a consumer protection statute in connection with the Site.
    </p>
    <h3>
      Links to Third Parties
    </h3>
    <p>
      For your convenience and to improve the usage of the Site, links to
      websites that are owned and controlled by third parties may be provided
      from time to time. These links take you outside Imogene’s service and off
      the Site and are beyond Imogene’s control. This includes links to partners
      that may use the Trade Marks as part of a co-branding agreement.
      The sites you can link to have their own separate terms and conditions
      as well as a privacy policy. Imogene is not responsible and cannot be held
      liable for the content and activities of these sites. You therefore visit/access
      these sites entirely at your own risk.

      Please note that these other sites may send their own cookies to users,
      collect data or solicit personal information, and you are therefore advised
      to check the terms of use and/or privacy policies on those websites
      prior to using them.
    </p>
    <h3>
      Misuse of the Site
    </h3>
    <p>
      You are prohibited from using the Site to post or transmit any User
      Generated Content (as defined below) which infringes or may infringe
      third party intellectual property rights or which is threatening, false,
      misleading, inflammatory, defamatory, invasive of privacy, obscene,
      pornographic, abusive, discriminating, illegal or which could constitute
      or encourage conduct that would be considered a criminal offence, violate
      the rights of any party or which may otherwise give rise to civil
      liability or violate any law. Imogene may deny you access to the Site
      at any time in its sole discretion and which shall include situations
      where Imogene believes that your use of the Site is in breach of any
      of these Terms and Conditions and/or applicable laws. You are further
      prohibited from using the Site to impersonate another person,
      user or Imogene staff, employee, or representative, imply that any
      statements you make are endorsed by Imogene, or post or transmit
      any material that could damage or disparage Imogene or any of
      its affiliate entities in any manner.

      You are also prohibited from using the Site to advertise or perform
      any commercial solicitation.

      You may not, while accessing or using the Site: request, or otherwise
      attempt to harvest, obtain or store, personal information, passwords,
      account information or any other type of information relating to other
      users; access or use another person&apos;s account; disguise the origin of
      any communications; alter, modify, frame, or &quot;mirror&quot; any Content; create
      a deep-link to our Site by by-passing our Site&apos;s homepage; use any data
      mining, robots, or similar data-gathering and extraction tools in
      connection with the Site; inhibit, disrupt, or otherwise prevent
      anyone from using or accessing the Site or interrupt any user&apos;s
      experience on the Site, including, but not limited to, acting
      in any manner that disrupts users&apos; real-time exchanges; interfere
      with or disrupt the Site, or servers or network connections
      to the Site, disobey any requirements, procedures, policies
      or regulations of networks connected to the Site; modify,
      adapt, sublicense, translate, sell, reverse engineer, decompile
      or disassemble any portion of the Site; or attempt to gain
      unauthorized access to the Site (or any portion thereof).
    </p>
    <h3>
      Changes to the Terms and Conditions
    </h3>
    <p>
      Imogene reserves the right, at its discretion, to change, modify,
      add, or remove portions of these Terms and Conditions at any time.
      If you continue to use the Site, check the footer for notice of
      changed Terms and Conditions. If the footer indicates that the
      Terms and Conditions have been changed, immediately read them.
      Your continued use of the Site after we have posted notice of such
      modifications, alterations or updates, and after you have had the
      opportunity to read the revised Terms and Conditions means you
      accept those changes.
    </p>
    <h3>
      Applicability of Additional Terms and Conditions
    </h3>
    <p>
      Additional or different terms and conditions (“Other Terms”) may
      apply in connection with certain features (e.g. community pages,
      testimonials, sweepstakes or contest entries). If applicable,
      these Other Terms will be set forth (i) where you are permitted
      to submit Content, access or use features, or purchase products
      and services, or (ii) in a link adjacent to where you are permitted
      to submit Content, access features, or purchase products and
      services. These Other Terms are incorporated into and made a
      part of these Terms and Conditions by reference. In the event
      Other Terms conflict with these Terms and Conditions, the Other
      Terms shall control with respect to the subject matter to
      which such Other Terms apply.
    </p>
    <h3>
      Export Control
    </h3>
    <p>
      Software and other materials from the Site may be subject to
      applicable export control laws that prohibit the export of certain
      technical data and software to certain territories. No software
      from the Site may be downloaded or exported (a) into any other
      country to which the United States has embargoed goods; or (b)
      anyone on the United States Treasury Department&apos;s list of Specially
      Designated Nationals or the U.S. Commerce Department&apos;s Table of Deny Orders.
      Imogene does not authorize the use, downloading or exportation of any software
      or technical data from the Site to any jurisdiction prohibited by
      applicable export laws and regulations.
    </p>
    <h3>
      Applicable law and jurisdiction
    </h3>
    <p>
      These Terms and Conditions shall be governed by the laws of Massachusetts.
      You and Imogene hereby submit to jurisdiction and venue in courts of
      the Commonwealth of Massachusetts.
    </p>
  </TextSection>
);

export default TermsPage;
