version: 2.1
jobs:
  start_app:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run:
          name: Setup Custom Environment Variables
          command: echo 'export CIRCLE_CI_RUN=true' >> $BASH_ENV
      - run:
          name: Install Chrome dependencies
          command: sudo apt-get install -y libxtst6 libnss3 libnspr4 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0 fonts-liberation xdg-utils
      - run:
          name: Download Chrome
          command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run:
          name: Install Chrome
          command: sudo dpkg -i google-chrome-stable_current_amd64.deb
      - run:
          name: Install client side dependencies
          command: cd client && yarn install
      - run:
          name: Install server side dependencies
          command: yarn install
      - run:
          name: Run client unit tests
          command: cd client && yarn test src/__tests__/unit/** -w 1
      - run:
          name: Start app
          command: yarn dev
          background: true
      - run:
          name: Run E2E tests
          command: yarn server:start && cd client && yarn wdio:run -l "silent"
workflows:
  version: 2
  build_and_test:
    jobs:
      - start_app:
          pre-steps:

